### ISSUE TITLE
slider value is not getting set for v1

### ISSUE THREAD

**Issue by secabhi** [angular-slider/angularjs-slider#224]
http://jsfiddle.net/7w755fLv/59/

**Comment by ValentinH** [comment]
What is the issue?

You are mentioning v1 but using v2 in your example..

**Comment by secabhi** [comment]
vm.priceSlider1 = {
        value: 50,
        floor: 10,
        ceil: 100        
    };
here my modal is set on value . but slider is showing max as 50
I want to do it for version 1 . sorry i haven't seen the version . please help me to do this with version 1

**Comment by secabhi** [comment]
??

**Comment by ValentinH** [comment]
Since I don't understand what you need, I can't help you. Please submit a clean request (btw this is an issue report page not support).

Also, I strongly advise you to use the latest version of the library.

If you really need to stay on v1, please explain your issue properly, with a fiddle showing this issue, etc...

For questions, it's preferable to use our gitter: https://gitter.im/angular-slider/angularjs-slider
