### ISSUE TITLE
Add ability to hide pointer text

### ISSUE THREAD

**Issue by edu2004eu** [angular-slider/angularjs-slider#273]
[Feature request]

It would be nice to have an option to hide the text above the pointer, so that we can show it elsewhere if need be. Just like the ability to hide the limit labels with `hideLimitLabels: true`.

It'd also be nice (either as an alternative to the above, or as an addition) to add a class other than `rz-bubble` to the pointer label, so that we can apply custom CSS on it.

Also, kudos for a very well working directive, and well written documentation :)

**Comment by ValentinH** [comment]
I'm ok to add a different class to the pointer labels.

Regarding the option to hide the label:
This was already requested in #99 and #248  , but I don't really want to add such a feature since we can do it with CSS:
````
.rz-bubble {
     display: none
}
```

All labels hidden: http://jsfiddle.net/2n4ay3oh/
Only the values ones: http://jsfiddle.net/fax330z1/

**Comment by gibybo** [comment]
I don't think this is really solvable with css alone. Sliding the handle to the side still causes the limit labels to disappear (to avoid overlapping the handle text that is no longer there) when they really should stay visible in this case.

**Comment by ValentinH** [comment]
@gibybo Good point, I might reconsider this... ;)

**Comment by ValentinH** [comment]
@jakobwinter This is what you mentioned in #295 .

**Comment by ValentinH** [comment]
I just add a hidePointerLabels option. I'll release it in 2.11 .
