### ISSUE TITLE
Slider for decimal showing too many decimal places

### ISSUE THREAD

**Issue by bplmp** [angular-slider/angularjs-slider#282]
1. Set a slider from 0.0 to 1.0
2. Translate the result to 0 to 100 by multiplying.

Demo: http://jsfiddle.net/7ptqcfeh/

### Expected behaviour
Show only round numbers 0-100.

### Actual behaviour
Get values like 15.999999999999996
![image](https://cloud.githubusercontent.com/assets/11858154/13438278/573d1c04-dfb6-11e5-8216-642ea782d704.png)

(Fixable by doing `return Math.round(value * 100) + '%';` on translate) http://jsfiddle.net/ttqofrpk/

**Comment by ValentinH** [comment]
When translate is used, the returned value is directly set to the labels because it can be a string or whatever.

Besides, when no translate function is provided and a decimal step is used, the rounding is already applied thanks to this function: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L1090 .

To conclude, this is not a bug and should be handled in the translate function if needed.

**Comment by bplmp** [comment]
Got it, thanks for the explanation!

**Comment by ppseprus** [comment]
[http://floating-point-gui.de/](Floating-point Arithmetic)

**Comment by bplmp** [comment]
Thanks, excellent resource!

**Comment by ppseprus** [comment]
Well, like the title said: "What Every Programmer Should Know"... : )
