### ISSUE TITLE
Jump incremental steps when clicking Slider Bar

### ISSUE THREAD

**Issue by jakobwinter** [angular-slider/angularjs-slider#296]
Right now, when clicking somewhere on the Slider Bar, the Pointer will jump straight to that point (or the nearest Tick).

As an additional option something like "**jumpDistance**" would be fantastic, where one can define the number of Ticks, the pointer will jump in the mouse direction, when clicking the Slider Bar.

So defining **jumpDistance: 10** and **step: 3** would make the Pointer jump 30 units with each click.

What do you think? Useful?

Cheers,
Jakokb

PS: This slider really is fantastic! So many options, yet so simple to use!

**Comment by apitts** [comment]
Somewhat related...when you click on the Slider Bar it would be nice if, for a range slider, the closest pointer jumped there rather than always the high pointer.

**Comment by ValentinH** [comment]
@jakobwinter I don't really like this feature. Indeed, when I use a slider that behaves like this, I feel it buggy. In my opinion, it's more logic that when I click at a point on the slider bar, it goes directly to this value. Also, I want to slow down the number of features that are added to this slider because it's becoming a white elephant.

@apitts the behaviour you described is already the one that is used in the 2.X version.
