### ISSUE TITLE
Webpack error

### ISSUE THREAD

**Issue by OrahKokos** [angular-slider/angularjs-slider#326]
### Steps to reproduce
1. Install webpack
2. Install slider
3. Require slider
4. Inject slider into the app

### Expected behaviour
Should initiate application

### Actual behaviour
On Inject breaks the application

**Comment by ValentinH** [comment]
I've never used webpack neither using this slider with the require syntax. However, it should be working since module is exported when used with CommonJS: https://github.com/angular-slider/angularjs-slider/blob/master/src/rzslider.js#L22

If you know Webpack, you might want to try fixing this issue and providing a pull request for it, it would be great!

**Comment by OrahKokos** [comment]
There is a workaround for now.
You need to manually require all files from the src folder ( You need to setup file-loader, less-loader )
When requiring the .js file, do not inject what is returned from require, but since webpack is aware of it, you can just inject it in the old fashioned way angular.module('testApp', ['rzModule']).

I'm booked for the time being, so this workaround will have to suffice.

**Comment by gaelduplessix** [comment]
You don't have to inject all the files manually, just the css. But indeed the `export`-ed value should be the module name as string, not the module object. This is how I workaround using es6 named imports:
```javascript
import { name as angularSlider } from 'angularjs-slider';
import 'angularjs-slider/dist/rzslider.css';

angular.module('myApp', [angularSlider]);
```

I'll send a PR to export the name instead of the module object
