### ISSUE TITLE
data binding issue: only works for input type: number

### ISSUE THREAD

**Issue by kimwandev** [angular-slider/angularjs-slider#352]
Please see demo: using angularjs currency filter

Demo:  http://jsfiddle.net/kimwan/649k42xp/ 

### Expected behaviour
Should be editable

### Actual behaviour
Input field not editable

**Comment by ValentinH** [comment]
In my opinion, it's weird to place the dollar sign inside the input field, because then the value becomes a string and the slider doesn't handle string.

Also, it's generally kinda hard to edit the slider value directly in an input box and you should use a intermediate variable to do so. Similar issue: #221
