### ISSUE TITLE
A time consuming callback with onChange leads to consecutive identical values

### ISSUE THREAD

**Issue by elishayer** [angular-slider/angularjs-slider#383]
When doing a big computation based on the `onChange` option, the callback will be called consecutively with the same value.

### Steps to reproduce
1. Do a big computation based the `onChange` callback
2. Quickly move the slider back and forth
3. Observe the value

Demo: http://jsfiddle.net/cwhgLcjv/109/

### Expected behaviour
All consecutive values logged to the console have different value.

### Actual behaviour
The same value is logged consecutively, as shown below
<img width="1280" alt="screen shot 2016-08-06 at 10 50 30 am" src="https://cloud.githubusercontent.com/assets/9312768/17457651/a3e9bb3c-5bc3-11e6-9fa2-3e5da352465b.png">

**Comment by ValentinH** [comment]
Indeed, this behaviour is not correct. I'll look into that when I have some time.

**Comment by ValentinH** [comment]
This issue only occurs in specific use-case and is due to the internal use of $evalAsync. Indeed, in some cases, when $evalAsync callback is called, the slider value has already changed and so another one will be fired for this change. This is a very low-level mechanism so not very easy to explain quickly. This article is a good reference: http://www.bennadel.com/blog/2605-scope-evalasync-vs-timeout-in-angularjs.htm 

Thus, what I advise you to do (and I've already done it for similar issue) is to use a `throttle` mechanism so you only call you heavy function once every X ms. A throttle is already used inside this library for other part of the code.
