### ISSUE TITLE
Any idea on how to use it in Angular 2.0 Apps?

### ISSUE THREAD

**Issue by chanusukarno** [angular-slider/angularjs-slider#395]

**Comment by ValentinH** [comment]
I dont know yet because I'm not using Angular 2. I know that there were library to integrate angular 1 module in 2 but I have never tried then.

Anyway for a performance setup, this library should be ported for Angular 2. I might do it one day if nobody has done it before, but I only do it if I actually need it otherwise I won't be good...

**Comment by ValentinH** [comment]
@chanusukarno  we now have a angular version: https://github.com/angular-slider/ng5-slider/tree/master 🎉
