### ISSUE TITLE
rzslider does not update correctly if in ng-if div

### ISSUE THREAD

**Issue by weisswurst** [angular-slider/angularjs-slider#457]
First time user here, please let me know if this is the right place to report this issue.

I have a slider that does not always behave correctly when it is behind an ng-if.
See the demo:

https://jsfiddle.net/weisswurst/zorjj2gv/10/

With the top slider, you can set a bid. The lowest possible bid is the  current highestBid+1.
If you set a bid with the slider and click the Bid button, the slider is correctly updated: the highestBid is set to the new bid, and the new lowest possible bid the again the highestBid+1. 

The lower slider, only visible after clicking the Toggle button, should behave exactly the same. 
But if you move the slider to some value higher than the lowest possible value and click the Bid button, then the highestBid is not updated correctly.

I first thought it had something to do with the $timeout issue, that is why I added the refreshSlider function. But I think something else is the problem.

**Comment by ValentinH** [comment]
This is a classic issue when starting with Angular: scope inheritance in child directives (ng-if in your case): I really advise you to read this nice article: https://github.com/angular/angular.js/wiki/Understanding-Scopes

Basically, your issue is that you bind a primitive value (integer here) inside a `ng-if` directive. This value is passed by value to the `ng-if` content and not by reference. Thus, when the child content updates the value, it is not reflected in the parent.

Here is the fixed fiddle: https://jsfiddle.net/L5svewh4/

**Comment by weisswurst** [comment]
Wow, thanks a lot for the fast response! Very nice article, ng-if creates a new scope, that is a real eye-opener.
Indeed, I just started with angular, sorry to have bothered you with something that appears to be a very common pitfall.

**Comment by ValentinH** [comment]
No worries, this is a complex part of Angular and it took me a while to really understand it when I started. In the article the say that you should always store your data with at least one '.' and it is indeed a good habit to take. I'm always setting by states in a main structure like $scope.model (actually vm.model if you follow good practices - you might want to read the angular style guide from John Papa as well ;)) and I haven't faced this issue since then.

**Comment by weisswurst** [comment]
Thanks once again! Awesome style guide.
