### ISSUE TITLE
Cannot get legend to display on slider bar

### ISSUE THREAD

**Issue by CodeLiftSleep** [angular-slider/angularjs-slider#490]
have Steps Array with values and legend, but nothing is showing up under the bar.  I have included the "with-legend" class in the slider element but still nothing.  I added the getLegend options but it is unclear exactly how to use it or what to do with it as none of the sliders have an example.  Honestly a simple example using getLegend or showing exactly how to get this working probably would have saved this issue from having to be created.  Documentation could definitely be better with these two things.  Examples are usually worth 1,000 words.

Demo: https://plnkr.co/edit/Qrvbn69f9usDH51DKdF0?p=preview

### Expected behaviour
Slider whould show all years and legends beneath each of them whether they are selected or not

### Actual behaviour
Slider only shows beginning and ending year along with selected year but no legends are displayed underneath them.

**Comment by ValentinH** [comment]
The legend system is demoed on the demo page: "Slider with ticks values and legend".
You were missing the  `showTicks` or `showTicksValues` attribute that is required (this is not clear in the documentation, my bad).

However, I'm not sure that this is what you want to achieve since you have a lot of text...
"Fixed" demo: https://plnkr.co/edit/RPafu9gVZSs9TdUyuWFK?p=preview

**Comment by ValentinH** [comment]
Closing as there was no answers for more than a month.

**Comment by megazoll** [comment]
Is it possible to show only legend, without showing ticks?

**Comment by ValentinH** [comment]
There is no option for this, but you could force the hiding of ticks via CSS.
