### ISSUE TITLE
Decimal values get skipped depending on width

### ISSUE THREAD

**Issue by atdiff** [angular-slider/angularjs-slider#513]
### Steps to reproduce
1. Using https://jsfiddle.net/ValentinH/954eve2L/
2. Scroll to the bottom of the page and test with the "Slider with all options demo"
3. Set step to 0.01, Precision of 2, Ceil to 10
4. Try to slide from 0.00 to 0.01, 0.02 or 0.03.
5. Adjust the width of the screen or the viewable area and repeat step 4.

Demo: http://jsfiddle.net/cwhgLcjv/ (fork this example and update the link)

### Expected behaviour
Should be able to go to every single decimal value from 0.00 to 10.00

### Actual behaviour
Depending on the width of the screen, it will skip values

**Comment by ValentinH** [comment]
This is not really a bug, this is due to the fact that there is not enough pixel to render all the steps. i don't see how we could fix that since the JS event listeners don't return floating pixel values.

However, when the precision is too slow, the user can use the keyboard arrows to adjust the value accurately.

**Comment by atdiff** [comment]
Seems odd that it isn't able to distinguish that like other sliders can. Shouldn't it be able to still calculate a position and place it regardless of the number of pixels?  It seems logical that the more important aspect is displaying all values rather than the real placement of the bar.

**Comment by ValentinH** [comment]
The issue is not about positioning a value on the slider but about reading the mouse position.

Let me show an example and please tell me if something feels wrong to you: :)
1. let's say we display a slider between 0 and 1000 with a step of 1 in a container of 200 pixels.
1. if the user moves the slider by 100 pixels from the left side of the container, the value should be 500.
1. now if the user moves the slider by 101 pixels, then the value should be 505 (`101 / 200 * 1000`).

If you wanted to set the slider to 501, you would need to move your mouse by 100.2 pixels which, as far as I know, is not possible.

**Comment by ValentinH** [comment]
The jQuery UI slider has the same issue: http://jsfiddle.net/z1ewvbou/
