### ISSUE TITLE
Semicolon missing is causing error!

### ISSUE THREAD

**Issue by wilson-boca** [angular-slider/angularjs-slider#603]
Hello Guys,

Once we use a minified JS with a lot of AngularJS components the latest version (6.4.1) is causing an error here.
In the rzslider.js line 2662 a semicolon is missing.
Maybe it is not causing error when used alone but we are facing problems here because of this.
I just add a semicolon and everything get back to work.
Could you please check it?

Rds,

Wilson Ferreira.

**Comment by ValentinH** [comment]
We would need to add this semicolon automatically in the build process.
For now, you can use the `rzslider.min.js` file which already has this semicolon ;)

**Comment by dackmin** [comment]
Same error here. The problem is that `rzslider.js` has been set up to be used with prettier (so it's actually missing a lot of semicolons), and even if `rzslider.min.js` is already prettified, `bower.json` `main` property uses `rzslider.js`, breaking projects using things like wiredep, usemin, uglify, ... and so on.

@wilson-boca you can temporarily fix it by overriding rzslider `bower.json` `main` property to use the minified version instead of the normal one.

I (personally) consider something like this to be a breaking change and it should be explicitly stated in the CHANGELOG or be a different major release 😄

**Comment by ValentinH** [comment]
My bad, when I moved to Prettier, I didn't expect this since we add a build process that was adding the semicolons.

To be safer, we have to add this final semicolons in the dist files.

**Comment by dackmin** [comment]
#588 might be the same problem

**Comment by ValentinH** [comment]
6.4.2 version should fix this issue. Let me know if it's not the case.

**Comment by wilson-boca** [comment]
Good morning,

Yes it's working fine now...

Thank you!!!
